#!/bin/bash
set -euo pipefail

POD_DIR="${FORUM_POD_DIR:-$HOME/Desktop/forum-stack/forum-pod}"
ANDROID_HOME="${ANDROID_HOME:-$HOME/android-sdk}"

cd "$POD_DIR"

if command -v java >/dev/null 2>&1; then
  JAVA_BIN="$(readlink -f "$(command -v java)")"
  JAVA_HOME_DETECTED="$(dirname "$(dirname "$JAVA_BIN")")"
  if [ -d "$JAVA_HOME_DETECTED" ]; then
    export JAVA_HOME="$JAVA_HOME_DETECTED"
  fi
fi

export ANDROID_HOME
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

echo "Using Node: $(node --version)"
echo "Using Java: $(java -version 2>&1 | head -n 1)"
echo "JAVA_HOME=$JAVA_HOME"
echo "ANDROID_HOME=$ANDROID_HOME"

if [ ! -d "$ANDROID_HOME" ]; then
  echo "Android SDK not found at $ANDROID_HOME"
  echo "Install it first, then rerun this script."
  exit 1
fi

echo "Wiping stale build outputs so a failed vite build cannot leave a misleading APK behind..."
rm -rf dist android/app/src/main/assets/public
rm -f android/app/build/outputs/apk/debug/app-debug.apk

echo "Installing Android app dependencies..."
npm install
npm prune
npm install @capacitor/core@6 @capacitor/cli@6 @capacitor/android@6 --save-dev --save-exact

CAP_MAJOR="$(node -e "console.log(require('./node_modules/@capacitor/cli/package.json').version.split('.')[0])")"
echo "Using Capacitor major: $CAP_MAJOR"

if [ -d android ] && grep -q "gradle:8.7.2" android/build.gradle 2>/dev/null && [ "$CAP_MAJOR" = "6" ]; then
  echo "Removing Android project generated by newer Capacitor/Java 21 toolchain..."
  rm -rf android
fi

echo "Building web assets for Android..."
VITE_BASE=./ npm run build

if [ ! -d android ]; then
  echo "Generating Capacitor Android project..."
  npx cap add android
else
  echo "Android project already exists."
fi

echo "Syncing web assets into Android project..."
npx cap sync android

if [ ! -x android/gradlew ]; then
  echo "Android project was generated, but android/gradlew is missing or not executable."
  echo "Open Android Studio with: npx cap open android"
  exit 1
fi

echo "Building debug APK..."
(cd android && ./gradlew assembleDebug)

if [ ! -f android/app/build/outputs/apk/debug/app-debug.apk ]; then
  echo "Gradle finished without producing app-debug.apk. Aborting."
  exit 1
fi

echo ""
echo "APK ready:"
echo "$POD_DIR/android/app/build/outputs/apk/debug/app-debug.apk"
